defaultConfiguration:
  create: true
  append: true
  flink-conf.yaml: |+
    kubernetes.operator.metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    kubernetes.operator.metrics.reporter.prom.port: 9999
metrics:
  port: 9999
operatorPod:
  annotations:
    metrics.dynatrace.com/port: "9999"
    metrics.dynatrace.com/scrape: "true"
    prometheus.io/port: "9999"
    prometheus.io/scrape: "true"